spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/config/assetmgmt, file:///E:/config/licensingservice
  profiles:
    active: native
  application:
    name: configservice
server:
  port: 8888